name: Pytest Check

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
#      - name: Install newer GCC
#        run: |
#          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
#          sudo apt-get update
#          sudo apt-get install gcc-13 g++-13
#          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
#          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
#      - name: Install GMT
#        run: sudo apt-get update && sudo apt-get install -y gmt libgmt-dev ghostscript

      - name: Define a cache dependency glob
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements**.txt"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests
