name: Type Check
on: [pull_request]
jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ty on runner
        run: pip install ty

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run type checking
        run: ty check --exclude setup.py --exclude nzgmdb/CCLD/ccldpy.py